-- Seed from Google Drive (Vendor Exposure Apr-Jun 2026, LABOUR CONTRACTOR LIST.xlsx).
-- Paste into the Neon SQL editor after schema.sql. Safe to re-run: existing names are skipped.

insert into companies (unit_id, name, category) values
  (null, 'Mittal Engineering Works', 'raw_material'),
  (null, 'Hi-Tech Steel & Tubes', 'raw_material'),
  (null, 'ACS Enterprises', 'raw_material'),
  (null, 'S Mahipal Steel', 'raw_material'),
  (null, 'India Steel', 'raw_material'),
  (null, 'N.S. Enterprises', 'raw_material'),
  (null, 'Ratnabhumi Steeltech Pvt. Ltd.', 'raw_material'),
  (null, 'Chaudhary Electric & Hardware Store', 'consumables'),
  (null, 'Mastertech Business Solutions Pvt Ltd', 'raw_material'),
  (null, 'Tushar Steel Traders', 'raw_material'),
  (null, 'MMST Enterprises', 'labour'),
  (null, 'Trimurti Engimetal and Steel Works Pvt Ltd', 'raw_material'),
  (null, 'Adira Enterprises', 'rent'),
  (null, 'Abhilash Tukaram Kalokhe', 'rent'),
  (null, 'Prakash Enterprises', 'consumables'),
  (null, 'Shree Om Enterprises', 'consumables'),
  (null, 'Raj Electrical Works', 'repair'),
  (null, 'Shree Krishna Steel', 'raw_material'),
  (null, 'Sunrise Traders', 'consumables'),
  (null, 'Mittal''s Colour World', 'consumables'),
  (null, 'MSEDCL (Mahavitaran)', 'other'),
  (null, 'Shrijee Sales Corporation', 'raw_material'),
  (null, 'Jagadguru Enterprises', 'consumables'),
  (null, 'Prince Enterprises', 'other'),
  (null, 'Apex Technologies', 'consumables'),
  (null, 'SS Enterprises', 'other'),
  (null, 'Neumet Engineers India Pvt Ltd', 'raw_material'),
  (null, 'Sunil Transport', 'transport'),
  (null, 'Urmi Oxygen Co.', 'consumables'),
  (null, 'Kishor HP Gas', 'consumables'),
  (null, 'MM Crane Services', 'transport'),
  (null, 'Delta Colour Chem Ind', 'consumables'),
  (null, 'Vipul J Solanki', 'other'),
  (null, 'Shri Swami Samarth Crane Services', 'transport'),
  (null, 'SaRSA Industries', 'labour'),
  (null, 'Noble Fastners', 'consumables'),
  (null, 'SP Auto Stamp LLP', 'labour'),
  (null, 'Miracle Enterprises', 'labour'),
  (null, 'S S Computers', 'other'),
  (null, 'Techno Tools', 'consumables'),
  (null, 'Pune NDT Services', 'other'),
  (null, 'Shiv Engineering & Dishing Works', 'other'),
  (null, 'Scan Laser', 'labour'),
  (null, 'A B Engineering & Fabrication', 'labour'),
  (null, 'Shah Marketing', 'raw_material'),
  (null, 'Vishal Management Services', 'other'),
  (null, 'AQ Tech Solutions', 'other'),
  (null, 'Ansh Enterprises', 'raw_material'),
  (null, 'Jay Bhole Water Supplier', 'other'),
  (null, 'Sairaj Welding Sales & Service', 'repair'),
  (null, 'Keval Incorporation', 'consumables'),
  ('savli', 'Baroda Steel & Metal Corporation', 'raw_material'),
  (null, 'Jay Ambe Enterprise', 'consumables'),
  (null, 'BRC Logistics', 'transport'),
  (null, 'Shree Balaji Tempo Service', 'transport'),
  (null, 'Kamla Hardware & Electricals', 'consumables'),
  (null, 'Shree Veena Enterprises', 'other'),
  (null, 'P.D. Combustion Air', 'consumables'),
  (null, 'Magtech Fasteners', 'consumables'),
  (null, 'Technomech Solution', 'repair'),
  (null, 'S. R. Industries', 'other'),
  (null, 'Shiv NDT Services', 'other'),
  (null, 'Electronics Devices Worldwide Pvt Ltd', 'consumables'),
  (null, 'Shree Agrasen Gases', 'consumables'),
  (null, 'Vaishnavi Enterprises', 'labour'),
  (null, 'Nirmal Engineers', 'labour'),
  ('savli', 'Vadodara Packaging & Safety Pvt. Ltd.', 'consumables')
on conflict (lower(name)) do nothing;

-- Labour contractors. The sheet has no unit column, so they go to Dehu; change the unit in Admin → Contractors if needed.
insert into contractors (unit_id, name) values
  ('dehu', 'Indal'),
  ('dehu', 'Walje'),
  ('dehu', 'Ranjit Sutar'),
  ('dehu', 'Gupta'),
  ('dehu', 'Kailash'),
  ('dehu', 'Arjun'),
  ('dehu', 'Vijay'),
  ('dehu', 'Tiwari'),
  ('dehu', 'Morales'),
  ('dehu', 'Verma'),
  ('dehu', 'Akhilesh'),
  ('dehu', 'Pandit')
on conflict (unit_id, lower(name)) do nothing;
